services:
  - type: web
    name: video-progress-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://user1:12vaibhav34890@mycluster.9py9n05.mongodb.net/video-progress
      - key: PORT
        value: 10000
        
    